### ISSUE TITLE
Enable configuring java GC and heap dump

### ISSUE THREAD

**Issue by trozet** [dfarrell07/puppet-opendaylight#104]
For debugging crashes when ODL runs out of ram or gets a sigkill we need should generate heap dumps.  Config needed to startup file:

 -XX:+HeapDumpOnOutOfMemoryError  -XX:HeapDumpPath=<path to dump file>

**Comment by vorburger** [comment]
@trozet @dfarrell07 we already have -XX:+HeapDumpOnOutOfMemoryError on DEFAULT_JAVA_OPTS in bin/karaf (at least on an ODL dist built locally today from an upstream current master = future Nitrogen release, based on Karaf 4 - but AFAIK I've added this quite a while ago already).

Dunno what HeapDumpPath is for - are you sure we need that? Probably to set the dir for the *.hprof ... without that it probably goes into the "working directory" of the Karaf JVM proc - not good enough? Not writeable, not working? (see http://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html and https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/clopts001.html)

Unless proven otherwise, I'm not sure this is really required.
